---
- name: Ansible Create user functionlity module demo
  hosts: web # Defining the remote server inventory host group
	# Defining the remote server where the ansible create user module 
  # will manage the objects
  remote_user: ubuntu # Using Remote user as ubuntu
  tasks:

	# name - Defines the username that is present or to create
	# groups - Adds users in secondary groups or use groups
	# state: present - Creates a user or works with a user
	# state: absent - Deletes a user
	# shell - Specifies shell-type a user can work on
	# home - Sets a user’s home directory
	# createhome: yes - Create a home directory for a user 
	# createhome: no - Do not create a home directory for a user

	# Creating the user Adam Listek 
    - name: Add the user 'Adam Listek' with a specific uid and a primary group of 'sudo'
      ansible.builtin.user:
        name: adamlis
        comment: AdamListek
        uid: 1077
        group: sudo
        createhome: yes        # Defaults to yes
        home: /home/adamlis    # Defaults to /home/<username>

	# Adding the user qa_editor in the editor group 
    - name: Add group "editor" to remote node
      group:
        name: qa_editor
        gid: 2212
        state: present

	# Adding the user Rochela in the qa_editor group and bash shell
    - name: Add the user 'Rochella' with a bash shell, appending the group 'editor' to the user's groups
      ansible.builtin.user:
        name: rochella
        shell: /bin/bash
        groups: qa_editor
        append: yes

# Removing the user shanky from the system 
    - name: Remove the user 'Shanky' if present in the linux system
      ansible.builtin.user:
        name: shanky3
        state: absent
        remove: yes